### ISSUE TITLE
Push wiki support to aced_rails

### ISSUE THREAD

**Issue by tschmorleiz** [danmichaelo/acewiki#1]
I am using ace with rails, therefore using https://github.com/ffloyd/aced_rails/. Problem is: It's missing wiki markup support :)

Would it be possible that you fork that repo, add _mode-wiki.js_ and _theme-wiki.js_ to it and send a pull request?
The files would need to be put in _vendor/assets/javascripts/ace_.

If you are ok with it, I can also do this. I already forked it, such that I can use your support for now like that, but did not send a pull request. I would of course add your name and repo to the comments.
Would be great if everyone using rails can benefit from your effort.

**Comment by danmichaelo** [comment]
Sorry I missed this one back in 2013.

https://github.com/ffloyd/aced_rails is now marked as abandoned, so I'm closing this.
